[package]
name = "example"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "example"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
example_integrity = { workspace = true }
private_event_sourcing = { path = "../private_event_sourcing" }
